name: rebase reuse

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      github_token:
        required: true
        type: string
jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{inputs.github_token }}

    - name: Check if branch is rebased
      run: |
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        git fetch origin
        latest_upstream_commit=$(git rev-parse origin/master)
        if git merge-base --is-ancestor $latest_upstream_commit $current_branch; then
            echo "The branch '$current_branch' has been rebased on 'origin/master'."
        else
            echo "The branch '$current_branch' has not been rebased on 'origin/master'."
            exit 1
        fi


  
    
