name: rebase reuse

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true
        
jobs:

  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
        #   token: ${{inputs.token }}

      - name: Check if branch is rebased
        run: |
          BASE_BRANCH=${{ inputs.base_branch }}
          git fetch origin
          BASE_COMMIT=$(git rev-parse origin/$BASE_BRANCH)
          CURRENT_BRANCH_BASE=$(git merge-base HEAD origin/$BASE_BRANCH)
          if [ "$BASE_COMMIT" == "$CURRENT_BRANCH_BASE" ]; then
            echo "The current branch has been rebased onto $BASE_BRANCH."
          else
            echo "The current branch has NOT been rebased onto $BASE_BRANCH."
            exit 1
          fi



  
    
