name: Check Rebase (Reusable)

on: 
  workflow_call:
    inputs:
      target_branch:
        type: string
        required: true
        description: 'The target branch to compare against (usually main)'

jobs:
  check-rebase:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check if rebased
      run: |
        git_hash=$(git rev-parse "$GITHUB_SHA")
        echo "branch commit: $git_hash"

        main_head=$(git rev-parse origin/${{ inputs.target_branch }})
        echo "Trunk head: $main_head"
        branch_source_commit_id=$(git merge-base "$git_hash" origin/${{ inputs.target_branch }})
        echo "First commit of this branch: $branch_source_commit_id"
        echo "branch_source_commit_id: |$branch_source_commit_id|"
        echo "main_head:               |$main_head|"
        
        if [[ "$branch_source_commit_id" != "$main_head" ]]; then
          echo "Error: you need to rebase with head ${{ inputs.target_branch }}"
          exit 1
        fi 
